/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpmbRouteImport } from './routes/spmb'
import { Route as KelompokBelajarRouteImport } from './routes/kelompok-belajar'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as IndexRouteImport } from './routes/index'

const SpmbRoute = SpmbRouteImport.update({
  id: '/spmb',
  path: '/spmb',
  getParentRoute: () => rootRouteImport,
} as any)
const KelompokBelajarRoute = KelompokBelajarRouteImport.update({
  id: '/kelompok-belajar',
  path: '/kelompok-belajar',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/berita': typeof BeritaRoute
  '/kelompok-belajar': typeof KelompokBelajarRoute
  '/spmb': typeof SpmbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berita': typeof BeritaRoute
  '/kelompok-belajar': typeof KelompokBelajarRoute
  '/spmb': typeof SpmbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/berita': typeof BeritaRoute
  '/kelompok-belajar': typeof KelompokBelajarRoute
  '/spmb': typeof SpmbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/berita' | '/kelompok-belajar' | '/spmb'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/berita' | '/kelompok-belajar' | '/spmb'
  id: '__root__' | '/' | '/berita' | '/kelompok-belajar' | '/spmb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeritaRoute: typeof BeritaRoute
  KelompokBelajarRoute: typeof KelompokBelajarRoute
  SpmbRoute: typeof SpmbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spmb': {
      id: '/spmb'
      path: '/spmb'
      fullPath: '/spmb'
      preLoaderRoute: typeof SpmbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kelompok-belajar': {
      id: '/kelompok-belajar'
      path: '/kelompok-belajar'
      fullPath: '/kelompok-belajar'
      preLoaderRoute: typeof KelompokBelajarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeritaRoute: BeritaRoute,
  KelompokBelajarRoute: KelompokBelajarRoute,
  SpmbRoute: SpmbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
